### ISSUE TITLE
Invalid env var seperator on bash

### ISSUE THREAD

**Issue by lafis** [roadster-rs/roadster#219]
```
roadster on  main is 📦 v0.3.2 via 🦀 v1.79.0
❯ export ROADSTER.ENVIRONMENT=development
bash: export: `ROADSTER.ENVIRONMENT=development': not a valid identifier
```

The '.' should be conventional a '_' to work on shells such as bash.

**Comment by spencewenski** [comment]
Thanks. I used `.` because I wanted to have different separators for the prefix and different levels of the config vs individual config field names (which would be in UPPER_SNAKE_CASE).

What do you think about using a double underscore (`__`) instead of `.` for the separator?
