### ISSUE TITLE
Allow running workers without redis?

### ISSUE THREAD

**Issue by ghost** [roadster-rs/roadster#6]
- Synchronous
- Async (via tokio)

Note: This could cause performance concerns, but might be useful for local development.

**Comment by spencewenski** [comment]
There are a few reasons why I don't find this useful at the moment:

- It's easy enough to set up a redis instance locally
- Running without redis requires us to either implement a separate retry mechanism or not have retries. In either case, the behavior of the workers would be different depending on whether redis is used or not, which is potentially confusing.
