### ISSUE TITLE
Set up `cargo-deny`

### ISSUE THREAD

**Issue by spencewenski** [roadster-rs/roadster#68]
It would be good to integrate with [cargo-deny](https://crates.io/crates/cargo-deny). However, at the moment it's too much a maintenance burden, so we will put this off for now.

**Comment by spencewenski** [comment]
This may see some of the same issues as <> :https://github.com/rust-lang/cargo/issues/10801, which results in vulns from disabled features/optional crates being included in the cargo.lock

**Comment by Jake-Shadle** [comment]
It won't, cargo-deny does not use the lockfile and does its own resolution graph pruning to workaround various cargo issues such as https://github.com/rust-lang/cargo/issues/10801.
